### ISSUE TITLE
being able to see the chart in garmin connect

### ISSUE THREAD

**Issue by bisti123** [individual-it/BatteryGuesstimate#12]
Would love that, might not be possible to make but would love it if it was possbile

**Comment by individual-it** [comment]
Interesting idea indeed, to display graphs one would need to create an activity and write to a FIT file https://developer.garmin.com/connect-iq/core-topics/activity-recording/
I wonder how that would be possible from a background task because we don't want to have every data point in a separate session. Need to find out if a session can stay open between the background tasks

**Comment by individual-it** [comment]
I had a deeper look into it and I think this is not possible currently because the `Fit` permission does not work for widgets.
Sorry
